import {StyleSheet, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('window');

export default StyleSheet.create({
  searchText: {
    fontSize: 14,
    color: 'black',
    width: width * 0.65,
    height: height * 0.05,
    paddingLeft: width * 0.03,
    marginTop: height * 0.05,
    marginLeft: width * 0.03,
    backgroundColor: 'white',
    borderRadius: 10,
    borderColor: 'gray',
    borderWidth: 1,
  },
  logoutButton: {
    backgroundColor: 'lightgray',
    height: height * 0.05,
    width: width * 0.1,
    marginTop: height * 0.05,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: width * 0.05,
    borderRadius: 10,
  },
  searchButton: {
    backgroundColor: 'white',
    borderColor: 'lightgray',
    height: height * 0.05,
    width: width * 0.1,
    marginTop: height * 0.05,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: width * 0.04,
    borderRadius: 10,
    borderWidth: 1,
  },
  shopName: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: width * 0.06,
    marginLeft: width * 0.05,
    marginTop: height * 0.03,
  },
  shopDetail: {
    color: 'lightgray',
    marginLeft: width * 0.05,
    marginTop: height * 0.03,
  },
  productsBox: {
    flexDirection: 'row',
    marginLeft: width * 0.05,
    marginTop: height * 0.03,
    justifyContent: 'space-between',
    // backgroundColor: 'red',
    alignItems: 'center',
  },
  products: {
    color: 'black',
    fontWeight: '500',
    fontSize: width * 0.05,
  },
  length: {
    color: 'lightgray',
    fontSize: width * 0.045,
  },
  showAll: {
    color: 'blue',
    fontWeight: '600',
    fontSize: width * 0.03,
    marginRight: width * 0.04,
  },
  noProduct: {
    color: 'black',
    fontSize: width * 0.04,
    marginVertical: height * 0.1,
  },
  addBox: {
    alignSelf: 'flex-end',
    marginTop: height * 0.001,
    marginRight: width * 0.04,
  },
});
